### PR TITLE
[Metal] Utilize -Fre to correctly size threadgroups

### LINKED ISSUE #452: [Metal][DXC] Concurrent writing of `uint4` components test failure
As illustrated in the `ComponentDataRace` test, Metal fails to correctly copy over the data when written concurrently across waves:

```
2025-09-24T18:54:33.7663560Z ******************** TEST 'OffloadTest-mtl :: WaveOps/ComponentDataRace.test' FAILED ********************
2025-09-24T18:54:33.7673620Z Exit Code: 1
2025-09-24T18:54:33.7673970Z 
2025-09-24T18:54:33.7674170Z Command Output (stdout):
2025-09-24T18:54:33.7674420Z --
2025-09-24T18:54:33.7674640Z Using Metal API
2025-09-24T18:54:33.7674870Z Created compute commands.
2025-09-24T18:54:33.7675090Z 
2025-09-24T18:54:33.7675220Z --
2025-09-24T18:54:33.7676900Z Command Output (stderr):
2025-09-24T18:54:33.7677860Z --
2025-09-24T18:54:33.7679250Z /Users/cbieneman/actions-runner/_work/offload-test-suite/offload-test-suite/llvm-project/build/bin/split-file /Users/cbieneman/actions-runner/_work/offload-test-suite/offload-test-suite/OffloadTest/test/WaveOps/ComponentDataRace.test /Users/cbieneman/actions-runner/_work/offload-test-suite/offload-test-suite/llvm-project/build/tools/OffloadTest/test/mtl/WaveOps/Output/ComponentDataRace.test.tmp # RUN: at line 64
2025-09-24T18:54:33.7681620Z + /Users/cbieneman/actions-runner/_work/offload-test-suite/offload-test-suite/llvm-project/build/bin/split-file /Users/cbieneman/actions-runner/_work/offload-test-suite/offload-test-suite/OffloadTest/test/WaveOps/ComponentDataRace.test /Users/cbieneman/actions-runner/_work/offload-test-suite/offload-test-suite/llvm-project/build/tools/OffloadTest/test/mtl/WaveOps/Output/ComponentDataRace.test.tmp
2025-09-24T18:54:33.7684220Z "/Users/cbieneman/actions-runner/_work/offload-test-suite/offload-test-suite/DXC/build/bin/dxc-3.7" -metal -T cs_6_5 -Fo /Users/cbieneman/actions-runner/_work/offload-test-suite/offload-test-suite/llvm-project/build/tools/OffloadTest/test/mtl/WaveOps/Output/ComponentDataRace.test.tmp.o /Users/cbieneman/actions-runner/_work/offload-test-suite/offload-test-suite/llvm-project/build/tools/OffloadTest/test/mtl/WaveOps/Output/ComponentDataRace.test.tmp/source.hlsl # RUN: at line 65
2025-09-24T18:54:33.7686860Z + /Users/cbieneman/actions-runner/_work/offload-test-suite/offload-test-suite/DXC/build/bin/dxc-3.7 -metal -T cs_6_5 -Fo /Users/cbieneman/actions-runner/_work/offload-test-suite/offload-test-suite/llvm-project/build/tools/OffloadTest/test/mtl/WaveOps/Output/ComponentDataRace.test.tmp.o /Users/cbieneman/actions-runner/_work/offload-test-suite/offload-test-suite/llvm-project/build/tools/OffloadTest/test/mtl/WaveOps/Output/ComponentDataRace.test.tmp/source.hlsl
2025-09-24T18:54:33.7699530Z /Users/cbieneman/actions-runner/_work/offload-test-suite/offload-test-suite/llvm-project/build/bin/offloader -debug-layer /Users/cbieneman/actions-runner/_work/offload-test-suite/offload-test-suite/llvm-project/build/tools/OffloadTest/test/mtl/WaveOps/Output/ComponentDataRace.test.tmp/pipeline.yaml /Users/cbieneman/actions-runner/_work/offload-test-suite/offload-test-suite/llvm-project/build/tools/OffloadTest/test/mtl/WaveOps/Output/ComponentDataRace.test.tmp.o # RUN: at line 66
2025-09-24T18:54:33.7702360Z + /Users/cbieneman/actions-runner/_work/offload-test-suite/offload-test-suite/llvm-project/build/bin/offloader -debug-layer /Users/cbieneman/actions-runner/_work/offload-test-suite/offload-test-suite/llvm-project/build/tools/OffloadTest/test/mtl/WaveOps/Output/ComponentDataRace.test.tmp/pipeline.yaml /Users/cbieneman/actions-runner/_work/offload-test-suite/offload-test-suite/llvm-project/build/tools/OffloadTest/test/mtl/WaveOps/Output/ComponentDataRace.test.tmp.o
2025-09-24T18:54:33.7704490Z 2025-09-24 13:54:33.574 offloader[39126:172017742] *** -[NSAutoreleasePool addObject:]: Do not use this instance method on specific pools -- just use -autorelease instead.
2025-09-24T18:54:33.7704960Z Test failed: ExpectedOut
2025-09-24T18:54:33.7705130Z Comparison Rule: BufferExact
2025-09-24T18:54:33.7705280Z Expected:
2025-09-24T18:54:33.7705380Z ---
2025-09-24T18:54:33.7705490Z Name:            ExpectedOut
2025-09-24T18:54:33.7705640Z Format:          UInt32
2025-09-24T18:54:33.7705760Z Channels:        4
2025-09-24T18:54:33.7705890Z Data:            [ 1, 2, 3, 4 ]
2025-09-24T18:54:33.7706040Z OutputProps:
2025-09-24T18:54:33.7706510Z   Height:          0
2025-09-24T18:54:33.7706640Z   Width:           0
2025-09-24T18:54:33.7706760Z   Depth:           0
2025-09-24T18:54:33.7706880Z ...
2025-09-24T18:54:33.7706970Z Got:
2025-09-24T18:54:33.7707060Z ---
2025-09-24T18:54:33.7707160Z Name:            Out
2025-09-24T18:54:33.7707290Z Format:          UInt32
2025-09-24T18:54:33.7707410Z Channels:        4
2025-09-24T18:54:33.7707540Z Data:            [ 1, 0, 0, 0 ]
2025-09-24T18:54:33.7707680Z OutputProps:
2025-09-24T18:54:33.7707790Z   Height:          0
2025-09-24T18:54:33.7708050Z   Width:           0
2025-09-24T18:54:33.7708170Z   Depth:           0
2025-09-24T18:54:33.7708290Z ...
2025-09-24T18:54:33.7708450Z Full Hex 64bit representation of Expected Buffer Values:
2025-09-24T18:54:33.7708670Z [ 0x1, 0x2, 0x3, 0x4 ]
2025-09-24T18:54:33.7708840Z Full Hex 64bit representation of Actual Buffer Values:
2025-09-24T18:54:33.7709890Z [ 0x1, 0x0, 0x0, 0x0 ]
2025-09-24T18:54:33.7710000Z 
2025-09-24T18:54:33.7710010Z 
2025-09-24T18:54:33.7710050Z --
2025-09-24T18:54:33.7710120Z 
2025-09-24T18:54:33.7710160Z ********************
```

### LINKED ISSUE #735: [Metal] Invalid DispatchThreadID value reported due to wrong pipeline group size setup
Found while working on https://github.com/llvm/offload-test-suite/pull/648

The shader outputs every threads values for some compute semantics like DispatchThreadID, GroupID, GroupThreadID  and GroupIndex.
The values are written to a large buffer with a unique key as index computed from the `GroupID` and the `GroupThreadId`. Reading https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/sv-groupid this should allow me to get a stable index no matter the order of scheduling: the index depends on the XYZ position, not the order.

The result is stable across DX and VK, but for MSL, the results are slightly off:
https://github.com/llvm/offload-test-suite/actions/runs/21940854135/job/63365919110?pr=648

In this run, the value `0x210008` is reported by Metal, while the expected value is `0x210002`.
`0x21` is the unique key computed in the shader.

Key is computed as follows:
`FID = thread index in the flat layout`
`KEY = FID * 12 + N`, with N being a value in `[0; 12[`
 (each thread outputs 12 values).

So we can compute back the thread index from this key:
- raw key: 0x21
- `0x21 == 2 * 12 + 9`
- this is thread 2 in the flat representation.

dispatch: `2x2x2`
numthreads: `2x2x2`.
This means we have 4 threads per line, 16 threads per plane.
This means the global thread coordinate here is: `x=2, y=0, z=0`
Which should be: `GroupID: x=1, y=0, z=0`, `GroupThreadID: x=0, y=0, z=0`, `GroupIndex: 2`, `DispatchThreadID: x=2, y=0, z=0`

The expected value in the test file is `0x210002`, which means we expect `DispatchThreadID.x` to be 2. But on Metal, this value is `8`. Which is I think impossible given dispatch.x is 2 and numthreads.x is 2.

### PR DESCRIPTION
**Pull request by llvm-beanz**
Several of the metal tests were failing due to incorrectly sized thread groups. This is because the Metal API takes the thread group size in the CPU API call not from the shader while Vulkan and DirectX both take the thread group size from the shader. To fix this we need to parse the shader reflection during configuring the dispatch pipeline.

This change uses the `-Fre` flag when targeting metal to dump shader reflection to a known filename, and then passes the reflection into the offloader. Doing this entirely inside lit macro expansions is a bit hacky, but I _think_ it's probably the right approach to keep our tests simple and run-lines agnostic to the runtime target.

Fixes #452, fixes #735

### CODE REVIEW

File: tools/offloader/offloader.cpp [hunk 1]
```diff
@@ -109,8 +114,12 @@ int run() {
   ExitOnErr(llvm::errorCodeToError(YIn.error()));
 
   // Read in the shaders
-  for (size_t I = 0; I < InputShader.size(); ++I)
+  for (size_t I = 0; I < InputShader.size(); ++I) {
     PipelineDesc.Shaders[I].Shader = readFile(InputShader[I]);
+    if (I < Reflection.size()) {
+      PipelineDesc.Shaders[I].Reflection = readFile(Reflection[I]);
+    }
```
Comment (inbelic) [inline tools/offloader/offloader.cpp]: nit:
```suggestion
    if (I < Reflection.size())
      PipelineDesc.Shaders[I].Reflection = readFile(Reflection[I]);
```
